name: Archive/develop

on:
  push:
    branches: develop

concurrency:
  group: archive-develop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  archive:
    name: develop
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: ci_post_clone
        run: |
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      # 署名は Upload ワークフローの書き出し時に App Store Connect API キーで行うので、ここでは署名しない
      - name: Archive
        run: |
          xcodebuild archive \
            -project OneTone.xcodeproj \
            -scheme OneTone \
            -sdk macosx \
            -configuration Release \
            -archivePath build.xcarchive \
            CODE_SIGNING_ALLOWED=NO
